version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: my_kafka_container
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my_kafka_container:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_MESSAGE_MAX_BYTES: 200000000
      KAFKA_REPLICA_FETCH_MAX_BYTES: 200000000
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  inventory-tracking-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: inventory-tracking-service
    depends_on:
      - mongo
      - kafka
    ports:
      - "3000:3000"
      - "9228:9228"
    env_file:
      - ./.env
    volumes:
      - ./src:/inventory-tracking-service/src
      - ./static:/inventory-tracking-service/static
      - ./test:/inventory-tracking-service/test
      - ./tsconfig.json:/inventory-tracking-service/tsconfig.json
      - ./tsconfig.build.json:/inventory-tracking-service/tsconfig.build.json
      - ./nest-cli.json:/inventory-tracking-service/nest-cli.json
    restart: always

volumes:
  mongo-data:
    driver: local
  kafka-data:
    driver: local
