version: "3"
services:
  mongo:
    image: mongo:latest
    container_name: my_mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  inventory-tracking-service:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: inventory-tracking-service
    ports:
      - "3000:3000"
      - "9228:9228"
    env_file:
      - ./.env
    volumes:
      - ./src:/inventory-tracking-service/src
      - ./static:/inventory-tracking-service/static
      - ./test:/inventory-tracking-service/test
      - ./tsconfig.json:/inventory-tracking-service/tsconfig.json
      - ./tsconfig.build.json:/inventory-tracking-service/tsconfig.build.json
      - ./nest-cli.json:/inventory-tracking-service/nest-cli.json
    restart: always

volumes:
  mongo-data:
    driver: local
