FROM node:18.13.0-alpine3.17

WORKDIR /inventory-tracking-service

COPY package*.json ./

RUN npm install

COPY ./scripts/populate.js ./scripts/populate.js

CMD node ./scripts/populate.js && npm run start:debug
