export enum HttpResponseMessage {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
  NOT_FOUND = "NOT FOUND",
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  PARTIAL_AVAILABILITY = "ONLY {number} PRODUCT ARE AVAILABLE IN STOCK",
  NO_AVAILABILITY = "OUT OF STOCK",
}
